version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"   # Default RabbitMQ Port
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: nimda
